### ISSUE TITLE
Bio::Root::Build has invalid pod

### ISSUE THREAD

**Issue by rocky** [bioperl/Bio-Root#1]
File _/Bio/Root/Build.pm_ has _=func_ which is invalid; _=head2_ would work. 

What gives?

**Comment by fjossandon** [comment]
Those '=func' where added in the commit https://github.com/bioperl/Bio-Root/commit/3f9968168918bfc802018f689ef1fc9114445cd8 by @carandraug, where it mentions dist zilla, but I'm don't handle the details. Maybe other devs can explain it...

**Comment by carandraug** [comment]
What do you mean is invalid? This is used to generate POD using pod weaver.  See [Pod::Weaver::PluginBundle::BioPerl](https://metacpan.org/pod/Pod::Weaver::PluginBundle::BioPerl)

Note the definition of func to define functions.

**Comment by rocky** [comment]
On Fri, Dec 19, 2014 at 2:42 PM, Carnë Draug notifications@github.com
wrote:

> What do you mean is invalid?

=func is is not Perl POD http://perldoc.perl.org/perlpod.html.  That
means you won't find it described anywhere in the official docs for POD.

> This is used to generate POD using pod weaver. See
> Pod::Weaver::PluginBundle::BioPerl
> https://metacpan.org/pod/Pod::Weaver::PluginBundle::BioPerl
> 
> Note the definition of func to define functions.

If you use something else to generate POD, then you shouldn't call this .pm
and should provide the post-proceeded files.

Some examples. In Perl, Build.PL is used to create Build, and Makefile.PL
is used to create Makefile. configure.ac is often used to create configure.
Makefile.am or Makefile.in is often used to create Makefile.

If someone copies Bio-Root/lib/Bio/Root/*.pm and puts them in
bioperl-live/Bio/Root and then runs tests you will get:

```
  t/PodSyntax.t .......................... 696/928
 #   Failed test 'POD test for Bio/Root/Build.pm'
 #   at /usr/local/share/perl/5.18.2/Test/Pod.pm line 186.
 # Bio/Root/Build.pm (47): Unknown directive: =func
 # Bio/Root/Build.pm (61): Unknown directive: =func
 # Bio/Root/Build.pm (133): Unknown directive: =func
 # Bio/Root/Build.pm (506): Unknown directive: =func
  ...
 # Looks like you failed 1 test of 928.
 t/PodSyntax.t .......................... Dubious, test returned 1
```

(wstat 256, 0x100)

If bioperl-live had some sort of DistZill preprocessing on this beforehand,
it might pass the test, but conceptually, I think it would still be wrong.

**Comment by carandraug** [comment]
On 19 December 2014 at 21:01, R. Bernstein notifications@github.com wrote:

> On Fri, Dec 19, 2014 at 2:42 PM, Carnë Draug notifications@github.com
> wrote:
> 
> > What do you mean is invalid?
> 
> =func is is not Perl POD http://perldoc.perl.org/perlpod.html. That
> means you won't find it described anywhere in the official docs for POD.
> 
> > This is used to generate POD using pod weaver. See
> > Pod::Weaver::PluginBundle::BioPerl
> > https://metacpan.org/pod/Pod::Weaver::PluginBundle::BioPerl
> > 
> > Note the definition of func to define functions.
> 
> If you use something else to generate POD, then you shouldn't call this .pm
> and should provide the post-proceeded files.
> 
> Some examples. In Perl, Build.PL is used to create Build, and Makefile.PL
> is used to create Make. configure.ac is often used to create configure.
> Makefile.am or Makefile.in is often used to create Makefile.
> 
> If someone copies Bio-Root/lib/Bio/Root/*.pm and puts them in
> bioperl-live/Bio/Root and then runs tests you will get:
> 
> ```
> t/PodSyntax.t .......................... 696/928
> # Failed test 'POD test for Bio/Root/Build.pm'
> # at /usr/local/share/perl/5.18.2/Test/Pod.pm line 186.
> # Bio/Root/Build.pm (47): Unknown directive: =func
> # Bio/Root/Build.pm (61): Unknown directive: =func
> # Bio/Root/Build.pm (133): Unknown directive: =func
> # Bio/Root/Build.pm (506): Unknown directive: =func
> ...
> # Looks like you failed 1 test of 928.
> t/PodSyntax.t .......................... Dubious, test returned 1
> (wstat 256, 0x100)
> ```
> 
> If bioperl-live had some sort of DistZill preprocessing on this beforehand,
> it might pass the test, but conceptually, I think it would still be wrong.

bioperl-live does not use DistZill but Bio-Root does (look into dist.ini). This means that if you were to use a released Bio-Root, the actual released files would have all the pod at the end, in a format that is more familiar to you.

You should not be copying files from one module repository into another and expect things to work out of the box. Bio-Root has not been released but neither has been any module that is depedent on it. So, please make a release of Bio-root and then copy those files.

[perlpodspec](http://perldoc.perl.org/perlpodspec.html) sounds a lot more flexible:

> Pod content is contained in Pod blocks. A Pod block starts with a line that matches <m/\A=[a-zA-Z]/>, and continues up to the next line that matches m/\A=cut/ or up to the end of the file if there is no m/\A=cut/ line.

By the way, although not used in Bio-Root, =attr and =method are others POD blocks
used in Bioperl modules that have been released independently from bioperl-live. I don't understand your surprise, this is very common syntax on many perl modules.

There are other things in the source that expect Pod Weaver. The following lines for example:

```
# ABSTRACT: module providing several methods often needed when dealing with file IO
# AUTHOR: Hilmar Lapp <hlapp@gmx.net>
# OWNER: Hilmar Lapp
# LICENSE: Perl_5

# CONTRIBUTOR: Mark A. Jensen <maj@fortinbras.us>
```

**Comment by rocky** [comment]
Ok. Thanks for the explanation.  

I don't have problem with Pod Weaver's extensions because it is compatible with existing Perl and PerlPod syntax. That Dist::Zilla chose to mess with the Pod Syntax is I think unfortunate, but that's not your fault. 

As I mention in livebio-perl, right now there are other unfortunate mismatches that are likely to lead to confusion. This project uses Dist::Zilla configuration while livebio-root doesn't. 
It also still has a vestige of Bio/Root inside it, and it does POD checking on that. And Test::PodChecker doesn't seem to accommodate for Dist::Zilla extensions. 

I'm sure folks can come up with great explanations for why all of this make sense, but the bottom line is the way things are now, it is awkward to develop from git.  The more awkward it is, the less likely people are going to contribute to this or the other project. See for example http://lists.ensembl.org/pipermail/dev/2014-December/010680.html

**Comment by carandraug** [comment]
The whole problem is that for the last 3-4 years there has been an effort to split bioperl-live into multiple smaller modules (because the whole thing is too large to manage). Some modules have been excised from bioperl-live but others remain. Some have been moved out of bioperl-live but have not been released, or were not removed completely.

This should have been a transition phase but seems like there is no one interested enough to finish the job.
